<a href="https://colab.research.google.com/github/cjsdudwls1/2026_Spring_Data_Standardization/blob/main/6%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# ==========================================
# 1. 행렬 형성 (Matrix Formation)
# 3a + 2b = 8
# 2a - b = 3
# ==========================================
A = np.array([[3, 2],
              [2, -1]])

B = np.array([[8],
              [3]])

print("--- 1. 행렬 A와 벡터 B ---")
print("A:\n", A)
print("B:\n", B)


# ==========================================
# 2. 행렬식(Determinant) 및 역행렬(Inverse)
# ==========================================
# 행렬식 계산 (이미지에서 역행렬 분모에 해당하는 -7)
det_A = np.linalg.det(A)

# 역행렬 계산
A_inv = np.linalg.inv(A)

print("\n--- 2. A의 행렬식 및 역행렬 ---")
print(f"행렬식 (det A): {det_A:.0f}")
print("역행렬 (A^-1):\n", A_inv)


# ==========================================
# 3. 단위행렬 확인 (A^-1 * A = I)
# ==========================================
# 파이썬에서 행렬의 곱셈은 '@' 연산자를 사용합니다. (np.dot과 동일)
I = A_inv @ A

print("\n--- 3. 단위행렬 확인 (A^-1 @ A) ---")
# 컴퓨터의 부동소수점 연산 오차 방지를 위해 반올림(round)하여 출력
print(np.round(I))


# ==========================================
# 4. 최종 해 구하기 (x = A^-1 * B)
# ==========================================
x = A_inv @ B

print("\n--- 4. 최종 해 [a, b] 계산 ---")
print(np.round(x))
print(f"\n👉 결과: a = {int(round(x[0][0]))}, b = {int(round(x[1][0]))}")

--- 1. 행렬 A와 벡터 B ---
A:
 [[ 3  2]
 [ 2 -1]]
B:
 [[8]
 [3]]

--- 2. A의 행렬식 및 역행렬 ---
행렬식 (det A): -7
역행렬 (A^-1):
 [[ 0.14285714  0.28571429]
 [ 0.28571429 -0.42857143]]

--- 3. 단위행렬 확인 (A^-1 @ A) ---
[[ 1.  0.]
 [-0.  1.]]

--- 4. 최종 해 [a, b] 계산 ---
[[2.]
 [1.]]

👉 결과: a = 2, b = 1
